//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode._2023.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode._2023.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xt36five77
        ///two8five6zfrtjj
        ///eightthree8fiveqjgsdzgnnineeight
        ///7chmvlhnpfive
        ///1tcrgthmeight5mssseight
        ///eightoneqxspfzjk4zpfour
        ///fdbtmkhdfzrck9kxckbnft
        ///9six9
        ///goneightczdzjk18589
        ///41two3eightfscdmqjhdhtvsixld
        ///t8929
        ///fourtwoxsxqqmqf3sixfoursixmmjhdlx
        ///bcbsfd14cjg
        ///95three6threendpqpjmbpcblone
        ///tdmvthreeonefive8574
        ///5eight82sixtwonev
        ///ninemg2shhmsqh
        ///thmlz4
        ///xtxjmm2tbbntrmdqxpkdjgh1vzjvtvg7nine
        ///vf19fourddfsvmzeight9
        ///mmg6fivegcthdonesix1eight
        ///7rzzdknxtbxdchsdfrkfivenjtbrjj
        ///2sdzxhxp
        ///vzvkjvngfjsxmponep9jpp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 1: 5 red, 1 green; 6 red, 3 blue; 9 red; 1 blue, 1 green, 4 red; 1 green, 2 blue; 2 blue, 1 red
        ///Game 2: 12 red, 2 green, 9 blue; 8 red, 12 blue; 9 red, 1 blue, 2 green; 12 blue, 8 red, 2 green; 4 red, 5 blue; 1 green, 9 blue, 10 red
        ///Game 3: 2 red, 8 blue, 5 green; 10 red, 10 green, 7 blue; 9 green, 13 red, 5 blue
        ///Game 4: 3 red; 1 blue, 3 green, 3 red; 3 blue, 8 green, 5 red; 8 green, 2 blue
        ///Game 5: 8 blue, 1 red, 1 green; 1 blue, 1 red, 7 green; 7 green, 5 blue
        ///Game 6: 2 red, 8 blue; 5 blue, 4 gre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
        ///...............415..*.........@......*...627*...................945*.............144/.506............................*......514...*...150...
        ///.........182..+.....873.756.......737........784..568....667..............258........./.........741...........707*....84........520.........
        ///..579...@.........$........*..........258.................*.........274..*.....739.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 467..114..
        ///...*......
        ///..35..633.
        ///......#...
        ///617*......
        ///.....+.58.
        ///..592.....
        ///......755.
        ///...$.*....
        ///.664.598...
        /// </summary>
        internal static string Day3_Example {
            get {
                return ResourceManager.GetString("Day3_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card   1: 18 39  5 97 33 74 70 35 40 72 | 62 23 33 94 18  5 91 74 86 88 82 72 51 39 95 35 44 87 65 15 46 10  3  2 84
        ///Card   2: 58 50 13 61 80 48 99 86 45 31 | 61 32 19  6 72 31 52 79 93 45 85 67 56 80  8  9 60 42 73 17 99 13 58 92 50
        ///Card   3: 65 10 18 47  8  4 99 51 71 48 | 85 87 88  8 48 18 47 67 95  4 99 86 53 51 65 44 61 10 28 14 77 71 21 58 42
        ///Card   4: 22 99 16 18 81  3 62 43  2 42 |  8 55 39 83 29 10 87 27 25 70 19 30 80 12  1 41 85 14 34 82 90 76  5 89 15
        ///Card   5: 23 45 94 25 59 75 22 97 62 57  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeds: 3037945983 743948277 2623786093 391282324 195281306 62641412 769611781 377903357 2392990228 144218002 1179463071 45174621 2129467491 226193957 1994898626 92402726 1555863421 340215202 426882817 207194644
        ///
        ///seed-to-soil map:
        ///3078006360 2182201339 30483272
        ///803630304 624445326 165226844
        ///2393736333 2745251526 281120946
        ///717936870 789672170 85693434
        ///598717319 410599330 27984688
        ///3999095007 2024628810 157572529
        ///3605588191 3026372472 22322803
        ///3555659576 2678166775 3396919
        ///968857148 438584018 1780307 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeds: 79 14 55 13
        ///
        ///seed-to-soil map:
        ///50 98 2
        ///52 50 48
        ///
        ///soil-to-fertilizer map:
        ///0 15 37
        ///37 52 2
        ///39 0 15
        ///
        ///fertilizer-to-water map:
        ///49 53 8
        ///0 11 42
        ///42 0 7
        ///57 7 4
        ///
        ///water-to-light map:
        ///88 18 7
        ///18 25 70
        ///
        ///light-to-temperature map:
        ///45 77 23
        ///81 45 19
        ///68 64 13
        ///
        ///temperature-to-humidity map:
        ///0 69 1
        ///1 0 69
        ///
        ///humidity-to-location map:
        ///60 56 37
        ///56 93 4.
        /// </summary>
        internal static string Day5_Example {
            get {
                return ResourceManager.GetString("Day5_Example", resourceCulture);
            }
        }
    }
}
